use_frameworks!

platform :ios, '10.0'

target 'ReloadlyAuthentication_Example' do
  pod 'ReloadlySDK/Airtime', :path => '../'
  pod 'ReloadlySDK/GiftCard', :path => '../'

  target 'ReloadlyAuthentication_Tests' do
    inherit! :search_paths

    
  end
end
