osx_image: xcode12.5
language: objective-c
script:
- pod lib lint --allow-warnings --no-clean
script:
  - xctool -project ReloadlyAuthentication.xcworkspace -scheme ReloadlyAuthentication-Example build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
